# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 014473a8dce6fab8d6574452a8910e165950669e8777b600e9c6528b79b8e35eab9f27d86ac7082b6f933e175ff2f96804fa8b720bca3a7aa822c896a47d6ddd

test:
  secret_key_base: 71549afcfeaa5d83e1b51f06287cf7d365b1f3f38bc6f2bbfc71e545c5c9b3525404f79489de0dc1a10f7e2490b2d3362a6c9f1a42a69a96cddc2231259eb0d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
